import { expandPresets, getExcludePresets, getWhitelistPresets } from "@/lib/filter-presets";
import type { ExcludeMode, FilterPattern, IceBoxFilterConfig } from "@/types";

function dedupePatterns(patterns: FilterPattern[]): FilterPattern[] {
  const seen = new Set<string>();
  const result: FilterPattern[] = [];

  for (const pattern of patterns) {
    const normalizedPattern = pattern.pattern.trim();
    if (!normalizedPattern) {
      continue;
    }

    const key = `${pattern.type}:${normalizedPattern}`;
    if (seen.has(key)) {
      continue;
    }

    seen.add(key);
    result.push({
      pattern: normalizedPattern,
      type: pattern.type,
      description: pattern.description?.trim() || undefined,
    });
  }

  return result;
}

export function resolveFilterPatterns(config: IceBoxFilterConfig): FilterPattern[] {
  if (config.mode === "disabled") {
    return [];
  }

  const presetPatterns = expandPresets(
    config.presets,
    config.mode === "whitelist" ? getWhitelistPresets() : getExcludePresets(),
  );

  return dedupePatterns([...presetPatterns, ...config.patterns]);
}

export function generateGitExcludeContent(config: IceBoxFilterConfig): string {
  if (config.mode !== "blacklist") {
    return "";
  }

  const lines = [
    "# Generated by Claw-Fridge backup filter",
    ...(config.inheritGitignore ? ["# Local .gitignore remains effective during git add"] : []),
  ];

  for (const pattern of resolveFilterPatterns(config)) {
    if (pattern.type === "glob") {
      lines.push(pattern.pattern);
      continue;
    }

    lines.push(`# regex:${pattern.pattern}`);
  }

  return `${lines.join("\n")}\n`;
}

function escapeForSingleQuotes(value: string): string {
  return value.replace(/'/g, `'"'"'`);
}

export function generateWhitelistCheckScript(config: IceBoxFilterConfig): string {
  if (config.mode !== "whitelist") {
    return "";
  }

  const patterns = resolveFilterPatterns(config);
  const globPatterns = patterns.filter((pattern) => pattern.type === "glob").map((pattern) => pattern.pattern);
  const regexPatterns = patterns.filter((pattern) => pattern.type === "regex").map((pattern) => pattern.pattern);

  const lines = [
    "matches_whitelist_path() {",
    '  local path="$1"',
    "",
  ];

  if (globPatterns.length > 0) {
    lines.push("  case \"$path\" in");
    for (const pattern of globPatterns) {
      lines.push(`    ${pattern}) return 0 ;;`);
    }
    lines.push("  esac", "");
  }

  if (regexPatterns.length > 0) {
    for (const pattern of regexPatterns) {
      lines.push(`  if printf '%s\n' "$path" | grep -E --quiet '${escapeForSingleQuotes(pattern)}'; then`);
      lines.push("    return 0");
      lines.push("  fi");
    }
    lines.push("");
  }

  lines.push("  return 1", "}");

  return `${lines.join("\n")}\n`;
}

export function formatFilterRulesForMarkdown(config: IceBoxFilterConfig): string {
  const patterns = resolveFilterPatterns(config);
  const modeLabel: Record<ExcludeMode, string> = {
    disabled: "禁用",
    blacklist: "黑名单",
    whitelist: "白名单",
  };

  const lines = [
    "## 备份过滤规则",
    "",
    `- 过滤模式：\`${config.mode}\`（${modeLabel[config.mode]}）`,
    `- 继承 .gitignore：\`${config.inheritGitignore ? "true" : "false"}\``,
    `- 预设：${config.presets.length > 0 ? config.presets.map((preset) => `\`${preset}\``).join(", ") : "`<none>`"}`,
    `- 生效规则数：\`${patterns.length}\``,
  ];

  if (patterns.length > 0) {
    lines.push("", "### 规则列表", "");
    for (const pattern of patterns) {
      lines.push(`- [${pattern.type}] \`${pattern.pattern}\`${pattern.description ? ` — ${pattern.description}` : ""}`);
    }
  }

  if (config.mode === "blacklist") {
    lines.push(
      "",
      "### 行为说明",
      "",
      "- 黑名单模式会优先尝试用生成的排除规则跳过不该进入备份的路径。",
      "- `regex` 规则无法直接写入 Git exclude 文件，脚本会在预筛选阶段额外处理。",
    );
  }

  if (config.mode === "whitelist") {
    lines.push(
      "",
      "### 行为说明",
      "",
      "- 白名单模式只允许匹配规则的路径进入暂存区，其他路径会被自动跳过。",
      "- 规则过少时，可能导致备份内容不完整；恢复前应先核对列表。",
    );
  }

  return lines.join("\n");
}

export function validateRegexPattern(pattern: string): { valid: boolean; error: string | null } {
  try {
    // 仅校验语法是否合法；实际匹配逻辑由服务端/调用方处理。
    new RegExp(pattern);
    return { valid: true, error: null };
  } catch (error) {
    return {
      valid: false,
      error: error instanceof Error ? error.message : "Invalid regular expression",
    };
  }
}
